-- QuestIdOverrides.lua
-- Generated by run_quest_lookup.py on 2026-02-26
-- Quest IDs fetched from Wowhead for quests missing IDs in scraped data
--
-- DO NOT EDIT MANUALLY - regenerate with: python tools/run_quest_lookup.py

local ADDON_NAME, addon = ...

addon.QuestIdOverrides = {
    ["A Last Resort"] = 66683,
    ["Augmenting a Dragon"] = 72515,
    ["Cheese for Glowergold"] = 13103,
    ["Draconic Decor"] = 92578,
    ["Dreamy Inspiration"] = 92577,
    ["Last Light"] = 92581,
    ["Last Steps"] = 33527,
    ["Learn From the Best"] = 51313,
    ["On New Wings"] = 76597,
    ["Pool of Visions"] = 33470,
    ["Return to Keeshan"] = 28183,
    ["Spare A Chair"] = 92580,
    ["The Bargain is Struck"] = 47432,
    ["The Downfall of Marl Wormthorn"] = 26187,
    ["The Jade Serpent"] = 30000,
    ["To Mechagon!"] = 55651,
}
