-- QuestIdOverrides.lua
-- Generated by run_quest_lookup.py on 2026-01-30
-- Quest IDs fetched from Wowhead for quests missing IDs in scraped data
--
-- DO NOT EDIT MANUALLY - regenerate with: python tools/run_quest_lookup.py

local ADDON_NAME, addon = ...

addon.QuestIdOverrides = {
    ["A Last Resort"] = 86891,
    ["Aln'hara's Bloom"] = 88995,
    ["Augmenting a Dragon"] = 72515,
    ["Cheese for Glowergold"] = 13103,
    ["Descent into the Rift"] = 86857,
    ["Draconic Decor"] = 92578,
    ["Dreamy Inspiration"] = 92577,
    ["Echoes and Memories"] = 86911,
    ["From this Point Forward"] = 90834,
    ["Halting Harm in Har'mara"] = 86973,
    ["Herding Manifestations"] = 86861,
    ["Into the Lightbloom"] = 86867,
    ["Last Light"] = 92581,
    ["Last Steps"] = 33527,
    ["Light Finds a Way"] = 86896,
    ["Nothing Stands Forever"] = 88706,
    ["On New Wings"] = 76597,
    ["Pool of Visions"] = 33470,
    ["Return to Keeshan"] = 28183,
    ["Root Dash Delivery"] = 91589,
    ["Russula's Outreach"] = 88997,
    ["Spare A Chair"] = 92580,
    ["The Bargain is Struck"] = 47432,
    ["The Cauldron of Echoes"] = 88994,
    ["The Downfall of Marl Wormthorn"] = 26187,
    ["The Echoless Flame"] = 88996,
    ["The Foundation of Aln"] = 86851,
    ["The Jade Serpent"] = 30000,
    ["The Traveling Flowers"] = 86956,
    ["To Mechagon!"] = 54088,
    ["Two Tons of Metal and Holy Fire"] = 88700,
    ["Wey'nan's Ward"] = 88993,
}
